### ISSUE TITLE
possible Bug: Victory Road Machoke hits a Dig pokemon using the move "Dual Chop"

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#104]
While going through Victory Road with a Dig using Sandslash, Machoke would constantly hit Sandslash underground when using the move Dual Chop. As far as my understanding goes, Dual Chop does not burrow into the ground and Machoke does not have an ability to hit pokemon off screen. Needs further research, if anyone wants to test this I would appreciate it.

**Comment by danenders** [comment]
An issue with the battle engine. Probably beyond my paygrade to fix / merging would be difficult with how out of date PokeClassic's base is. Going to pass on this.

**Comment by DaniRainbow** [comment]
For the ones that you won't fix but would be in the spirit of the hack,
would you merge pull requests? I don't mind taking a crack at some of these
like I am with the Moltres issue but if pull requests are always going to
be closed on principle instead of merged I may just post how I fixed things
instead. I appreciate your hard work on this hack, just curious if you
would accept contributions to the code or if it's a solo endeavor.

**Comment by danenders** [comment]
So some of the ones that I closed the pull requests for were because they were known issues and I had already been working on my changes locally; so going forward, once I knock out most of these reported/investigated ones, I don't think I'd be opposed to accepting merges!

I'm going to try and hit the last few big ones (Mewtwo, Moltres, and Cedar), but after that I likely won't be doing many fixes/investigating on my own.

**Comment by DaniRainbow** [comment]
Cool, thanks for letting me know
