### ISSUE TITLE
Bug: trapped in Seafoam Island

### ISSUE THREAD

**Issue by ttdevmode93** [danenders/pokeclassic#63]
Upon returning to Seafoam Island  (via Cinnabar) after catching Articuno, the player will be trapped in the water if they try to surf. This is because the boulders are missing and there is no way to escape the cave except for an escape rope.

**Comment by DaniRainbow** [comment]
I can confirm, instead of getting the "water to fast to surf" message, you go in and then get stuck at the bottom of the waterfall. This is a soft lock without Teleport, Dig, or Escape Rope

**Comment by DaniRainbow** [comment]
This may require more testing, as there are two different sources of running water. One is a waterfall that I got stuck on by surfing into the rapids. The exit for that doesn't work if you surf but if you drop through a hole above there into the water, your character goes down the waterfall and into the calm water of another map as intended.

@ttdevmode93 did you experience getting stuck on the left rushing water source that leads to Articuno when calm or the one on the right that goes down the waterfall like I did?

**Comment by danenders** [comment]
Fixed. 
- Added a current tile to prevent the player from being able to surf past the 'fast' area if you're entering Seafoam from the exit and haven't solved the puzzle.
- Corrected an error with the B4 boulders; they were still trying to use a a 'compare' macro for their variable instead of just checking if it was equal or not. Puzzle should now remain solved after exiting Seafoam/encountering Articuno.

**Comment by DaniRainbow** [comment]
I performed more testing and could not get stuck no matter how hard I tried. Thank you!
