### ISSUE TITLE
Bug: Moltres missing from Victory Road

### ISSUE THREAD

**Issue by ttdevmode93** [danenders/pokeclassic#66]
![image](https://github.com/danenders/pokeclassic/assets/136347247/f9a94866-fffb-469a-b647-9e06302b6db1)

The cave in the back of the pic can't be entered either. I have beaten the elite 4, if that matters.

**Comment by ZhugeLain** [comment]
how do you get to this spot in VR?

**Comment by ZhugeLain** [comment]
> ![image](https://user-images.githubusercontent.com/136347247/245982681-f9a94866-fffb-469a-b647-9e06302b6db1.png)
> 
> The cave in the back of the pic can't be entered either. I have beaten the elite 4, if that matters.

How do you get to this spot in VR?

**Comment by ttdevmode93** [comment]
Just go to the place where Moltres usuaLly is in Yellow, and you'll see it.

**Comment by DaniRainbow** [comment]
I'm currently investigating this issue. The warp Event on the cave door is properly pointing to the room Moltres is in and the collision detection is no different from other caves but the player cannot walk into the cave door tile and activate the warp. I changed the collision to match a door and put a door tile there and in the compilation, the door did not appear but all ladders in Victory Road went to the bottom right ladder of Victory Road 2F. Opening the file in porymap shows that the ladder warps are still pointing to the right places so something is not quite right. This is my priority issue because this is now the only thing preventing a player from completing the Pokedex.

**Comment by DaniRainbow** [comment]
Good news: I was able to find collision detection and a cave entrance tile that allows a player to enter in to Moltres's room and catch the Moltres. 

Bad news: Despite not changing ANY of the warps, most ladders and doors are now bugged. Exiting Moltres room leads to the first 2F ladder, going down that ladder leads to the Victory Road entrance, going out of Victory Road teleports the player to the south side of Route 23. I ran around Viridian City and Pallet Town to see if anywhere else got messed up warps but thankfully the issue is contained to the Victory Road maps.

In Yellow, I believe Moltres was just in the crater of Victory_Road_2F instead of in a separate room. Perhaps it would be better to remove this extra chamber and re-create the Pokemon Yellow interaction?

**Comment by MrMazzone** [comment]
My vote goes to we have Moltres appear in the crater. Would it be with a flag that you have to be champion for Moltres to appear?

**Comment by DaniRainbow** [comment]
> My vote goes to we have Moltres appear in the crater. Would it be with a flag that you have to be champion for Moltres to appear?

I believe that wasn't a requirement in Yellow but I may be mistaken. The Moltres encounter in the chamber is formatted differently than Zapdos and Articuno but it should be possible to add those script options to the Victory Road with some changes, including moving two items. I'll start trying to merge the scripts as I can.

**Comment by danenders** [comment]
This has been fixed. Changed the tiles a bit, but Moltres' room is now accessible.

**Comment by DaniRainbow** [comment]
Did you happen to test if the warps get messed up in Victory Road? If not I
can compile this latest one and check.

**Comment by danenders** [comment]
Warps should remain intact.

**Comment by DaniRainbow** [comment]
I'll test this when I can. Any effort I made ruined the warps even though
porymap indicated no changes were made to them

**Comment by danenders** [comment]
No rush; but wait a day or two and I should have a version pushed up that also has the aide calls fixed. I think the last big thing I need to knock out is the softlock in Seafoam.

**Comment by DaniRainbow** [comment]
Cool! I'll wait till I hear back.

**Comment by DaniRainbow** [comment]
Definitely fixed. I also didn't experience any of the previous warp issues. Thanks!

https://imgur.com/a/Oc3aWgw
